### ISSUE TITLE
DISTRO fails to resolve in idt-installer script on ubuntu 18.04

### ISSUE THREAD

**Issue by esberglu** [IBM-Cloud/ibm-cloud-developer-tools#102]
**Summary**
The idt-installer script (master) is failing on ubuntu. The DISTRO variable is no longer resolving correctly after https://github.com/IBM-Cloud/ibm-cloud-developer-tools/commit/5ea4b534101196eda96199b01b242c61beaba25c

**Steps to reproduce**
1.  Run the idt-installer script on ubuntu 18.04
`curl -sL https://ibm.biz/idt-installer | bash`

**Operating System**
Ubuntu 18.04

**Supporting details**
Script failure
```
[main] --==[ IBM Cloud Developer Tools for Linux/MacOS - Installer, v1.2.3 ]==--
[main] WARN: Linux has only been tested on Ubuntu, RedHat, Centos & Debian distrubutions please let us know if you use this utility on other Distros
[install] Starting Update...
[install_deps] ERROR: This script has not been updated for use with your linux distribution ()
The command '/bin/sh -c curl -sL https://ibm.biz/idt-installer | bash' returned a non-zero code: 255
```

DISTRO variable not resolving correctly
```
root@6e93b2ab61b5:/# DISTRO=$(lsb_release -ds 2>/dev/null || cat /etc/*release 2>/dev/null | head -n1 || uname -om || echo "")
root@6e93b2ab61b5:/# echo $DISTRO
DISTRIB_ID=Ubuntu
root@6e93b2ab61b5:/# DISTRO=$(lsb_release -ds 2>/dev/null || cat /etc/redhat-release 2>/dev/null | head -n1 || cat /etc/*release 2>/dev/null | head -n1 || uname -om || echo "")
root@6e93b2ab61b5:/# echo $DISTRO

root@6e93b2ab61b5:/#
```

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by jSunnari** [comment]
I'm having the same problem in Debian:

```

[main] --==[ IBM Cloud Developer Tools for Linux/MacOS - Installer, v1.2.3 ]==--
[main] WARN: Linux has only been tested on Ubuntu, RedHat, Centos & Debian distrubutions please let us know if you use this utility on other Distros
[install] Starting Update...
[install_deps] ERROR: This script has not been updated for use with your linux distribution ()
```

I've tried setting the DISTRO variable manually but it just disappears.

**Comment by esberglu** [comment]
I think the problem is that the file in the subcommand `cat /etc/redhat-release` only exists in RHEL. I suspect all other distros are broken.

**Comment by steveclay** [comment]
Reverted the problem commit.
