### ISSUE TITLE
Add support to Linux@IBM Clients moving Red Hat

### ISSUE THREAD

**Issue by steveclay** [IBM-Cloud/ibm-cloud-developer-tools#104]
**Summary**
PR #101 attempted to add support for this version of Linux, but the change resulted in #102 . We need to work out a solution that works for both scenarios.

**Steps to reproduce**
(include tooling version, platform, etc)
1. Install on the various Linux distros.

**Operating System**
Specify: (MacOS, Linux, Windows) - Linux

**Comment by jcfaracco** [comment]
@steveclay there is a second file that we use here to find version: /etc/openclient-release

I tried to be simple, but now I see that it caused problems. Well, this file can be a solution.
