### ISSUE TITLE
curl -sL https://ibm.biz/idt-installer | bash failed on RedHat

### ISSUE THREAD

**Issue by gajaka** [IBM-Cloud/ibm-cloud-developer-tools#106]
**Summary**
I am getting the following error since today . All worked fine yesterday.
curl -sL https://ibm.biz/idt-installer | bash
bash: line 487: syntax error in conditional expression: unexpected token `;'
bash: line 487: syntax error near `;'
bash: line 487: `    if [[ "$DISTRO" != *Ubuntu* &&  "$DISTRO" != *Red*Hat* && "$DISTRO" != *CentOS* && "$DISTRO" != *Debian* && "$DISTRO" != *RHEL*]]; then'

**Steps to reproduce**
curl -sL https://ibm.biz/idt-installer | bash

**Operating System**
Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Supporting details**

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by skyfoxby** [comment]
I have the same error on  Ubuntu 16.04.5 LTS (Xenial)
$ curl -sL https://ibm.biz/idt-installer | bash

```
bash: line 487: syntax error in conditional expression: unexpected token `;'
bash: line 487: syntax error near `;'
bash: line 487: `    if [[ "$DISTRO" != *Ubuntu* &&  "$DISTRO" != *Red*Hat* && "$DISTRO" != *CentOS* && "$DISTRO" != *Debian* && "$DISTRO" != *RHEL*]]; then'
```

**Comment by schmidtp0740** [comment]
Please test again. new commits were merged to patch this.

**Comment by gajaka** [comment]
I will give try tomorrow morning and will notify you. Thanks for the fix.

**Comment by skyfoxby** [comment]
Thank you. It works for me

**Comment by gajaka** [comment]
Sorry for the late answer. Works fine. Thanks
