### ISSUE TITLE
IDT tool does not respect Swift Package Manager conventions

### ISSUE THREAD

**Issue by gmosx** [IBM-Cloud/ibm-cloud-developer-tools#11]
I tried to create a new Swift-based WebApp project using `MyCoolProject` as project name.
I was surprised to see the generated directory be named `mycoolproject`, i.e. all lowercase.
That goes against Swift directory name conventions (CamelCase is expected).

**Comment by kfbishop** [comment]
We originally had issues with special characters in project names, and there was work to sanitize the name.  I can't offer an explanation about the case change though.  I've created an internal issue and will update this item once its being addressed.
BTW -- Thanks for the feedback and issues!

**Comment by kfbishop** [comment]
This item is being actively addressed, and should be resolved in our next minor release (~Oct timeframe?)

**Comment by kfbishop** [comment]
Should be resolved in v1.1 release of IDT CLI
