### ISSUE TITLE
Windows CLI installer doesn't work with HTTPS URL

### ISSUE THREAD

**Issue by jpkessle** [IBM-Cloud/ibm-cloud-developer-tools#115]
It has come to my attention that the windows installer script command (found [here](https://cloud.ibm.com/docs/cli?topic=cloud-cli-ibmcloud-cli#overview)), does not use *https*.

Windows installer command:
```
Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')
```

I tried using https in the URL and it fails with:
```
PS C:\Users\jpkessle>> Set-ExecutionPolicy Unrestricted; iex(New-Object net.WebClient).DownloadString('https://ibm.biz/i
dt-win-installer')

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"):
Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:35
+ ... restricted; iex(New-Object Net.WebClient).DownloadString('https://ibm ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

- [ ] Investigate why the installer fails when using https url. We should be setting an example with higher security standards and use https instead of http.
- [ ] Once the issue is fixed, notify Josh Kessler so he can update the command syntax in all affected CLI topics. Please update this [doc issue](https://github.ibm.com/Bluemix/docs/issues/4278).

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by schmidtp0740** [comment]
The reason why we used `http://ibm.biz/idt-win-installer` is that the `https://ibm.biz/idt-win-installer` link uses TLS1.2 (I verified by testing with [sslabs.com](https://www.ssllabs.com/ssltest/analyze.html?d=ibm.biz)) and [powershell's default security protocol is TLS1.0](https://docs.microsoft.com/en-us/security/solving-tls1-problem). That is why we see an error that powershell could not create a secure connection.

To resolve this issue, a possible fix may be 
```
[Net.ServicePointManager]::SecurityProtocol = "Tls12, Tls11, Tls, Ssl3"; iex(New-Object Net.WebClient).DownloadString('https://ibm.biz/idt-win-installer')
```

Ive tested on my windows machine but if we could test this on a fresh windows machine then we should be confident in this solution.

**Comment by jpkessle** [comment]
@schmidtp0740 - I'm testing it on my Windows 10 system now. I'll post my results shortly.

**Comment by jpkessle** [comment]
@schmidtp0740 - The command worked fine on my Windows laptop.

**Comment by jpkessle** [comment]
@schmidtp0740 @steveclay - Were you able to do any more Windows testing with the https command? I also noticed our topic for [installing the standalone CLI](https://cloud.ibm.com/docs/cli?topic=cloud-cli-install-ibmcloud-cli) uses an https url:
```
iex(New-Object Net.WebClient).DownloadString('https://clis.cloud.ibm.com/install/powershell')
```

I suspect that this command would fail in the same way the Developer tools script fails. I need to confirm this on my Windows system. If it fails, we will need to test the updated command syntax for this command too, then I can update both commands syntax to use https in the docs.

**Comment by jpkessle** [comment]
@schmidtp0740 @steveclay - Do you guys have any more feedback on this? Can we confirm that the command no longer needs the `Set-ExecutionPolicy Unrestricted;` but when we update the doc syntax to use https url, add the `[Net.ServicePointManager]::SecurityProtocol = "Tls12, Tls11, Tls, Ssl3";`.

I am leaving for vacation tomorrow, was just hoping to get this one closed out before I'm gone. (I'll be gone for almost 3 weeks) If you guys need more time, no problem, I'll just give your contact info to my back up.

**Comment by cdmauney** [comment]
@schmidtp0740 @steveclay Any additional feedback on this?

**Comment by steveclay** [comment]
Our testing looks good. We will put this in a PR today @cdmauney .

**Comment by cdmauney** [comment]
@jpkessle FYI.

**Comment by jpkessle** [comment]
@steveclay If you can confirm the command syntax, I am happy to update the topic. Do we still need to use `Set-ExecutionPolicy Unrestricted;`? Or we can just use the following command:

`[Net.ServicePointManager]::SecurityProtocol = "Tls12"; iex(New-Object Net.WebClient).DownloadString('https://ibm.biz/idt-win-installer')`

Thanks!

**Comment by steveclay** [comment]
Missed the above question. The only thing that changes is substituting this command. All else stays the same for the exec policy, etc.
