### ISSUE TITLE
'bluemix.exe' and 'bx.exe' seem to be copies of 'ibmcloud.exe' in the same folder

### ISSUE THREAD

**Issue by tuyt-ch** [IBM-Cloud/ibm-cloud-developer-tools#145]
**Summary**
`bluemix.exe` and `bx.exe` seem to be copies of `ibmcloud.exe` in the same folder. instead creating exact copies use `bat` scripts, similar to `ic.bat`.
However I couldn't figure it out if they are installed by IDT, ibmcloud installer, a plugin, or in any other way.

**Steps to reproduce**
(include tooling version, platform, etc)
1. see files in C:\Program Files\IBM\Cloud\bin

**Operating System**
Specify: Windows

**Supporting details**
![2019-11-08 01_58_42-C__Program Files_IBM_Cloud_bin](https://user-images.githubusercontent.com/28097800/68441134-77ea7900-01cd-11ea-88c0-a862a13767b1.png)

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by steveclay** [comment]
The bluemix.exe, etc. are installed by the ibmcloud installer as a convenience to users, versus the batch file created by the IDT installer.
