### ISSUE TITLE
install script on MacOS does not install Docker

### ISSUE THREAD

**Issue by tim-gp** [IBM-Cloud/ibm-cloud-developer-tools#174]
**Summary**
I've just run the install script on a fresh Big Sur install and the Docker install step does not complete successfully.

**Steps to reproduce**
(include tooling version, platform, etc)
1. `curl -sL https://raw.githubusercontent.com/IBM-Cloud/ibm-cloud-developer-tools/master/linux-installer/idt-installer | bash`

**Operating System**
Specify: (MacOS, Linux, Windows)
macOS Big Sur

**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)
```
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
[install_darwin_deps] Please review any setup requirements for 'docker' from: https://docs.docker.com/engine/installation/
```

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by tim-gp** [comment]
This is the correct command:
```
brew install --cask docker
```

**Comment by tim-gp** [comment]
Also noticed the shell completion isn't working either:
```
grep: : No such file or directory
bash: line 375: ${env_file}: ambiguous redirect
```

**Comment by steveclay** [comment]
Brew install corrected.

**Comment by steveclay** [comment]
The script is assuming one of these files will be found. Perhaps not so on your system?

~/.bashrc
~/.bash_profile
~/.profile

**Comment by tim-gp** [comment]
Hi @steveclay and thank you. MacOS defaults to `zsh` now, so may be worth adding `.zshrc`?

It wouldn't have helped me as my install was so fresh, I hadn't created it yet!

**Comment by steveclay** [comment]
Thanks, this is now added as well.
