### ISSUE TITLE
Docker image is missing curl

### ISSUE THREAD

**Issue by MrKrabat** [IBM-Cloud/ibm-cloud-developer-tools#176]
**Summary**
Your documentation states that your Docker image `ibmcom/ibm-cloud-developer-tools-amd64` should contain curl, but it does not.
https://cloud.ibm.com/docs/cli?topic=cli-using-idt-from-docker

**Steps to reproduce**
(include tooling version, platform, etc)
1.  `docker pull ibmcom/ibm-cloud-developer-tools-amd64:latest`
2.  `docker run -ti ibmcom/ibm-cloud-developer-tools-amd64:latest`
3.  `curl`
4. curl not found

**Operating System**
Specify: does not apply

**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)
```
~ # curl
/bin/sh: curl: not found
```

**Comment by steveclay** [comment]
Thank you for pointing out this discrepancy. We will correct the documentation to match the image.
