### ISSUE TITLE
Force (re)installation of dependencies

### ISSUE THREAD

**Issue by triceam** [IBM-Cloud/ibm-cloud-developer-tools#20]
**Summary**
Add a `--force` option to force dependency installation, rather than skipping if already installed.

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by kfbishop** [comment]
Should we consider a `clean` action for projects to wipe out all transient content, like modules, containers, etc?

**Comment by triceam** [comment]
Yes, for sure.  Would you expect this to be a separate action, or just part of the `--force` process?   I'm thinking this might be default as part of `--force`.

**Comment by kfbishop** [comment]
added `--force` args to "idt update" (shell and bat) files for forced updates of deps.
