### ISSUE TITLE
Unable to Install IBM Cloud Developer Tools on Windows

### ISSUE THREAD

**Issue by nurivpr** [IBM-Cloud/ibm-cloud-developer-tools#21]
Getting several errors on Windows powershell when I try to install using the following command

Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')

Error Screens:
![image](https://user-images.githubusercontent.com/32694031/31421032-a4ed03e2-ae77-11e7-9875-784e83af038c.png)

**Comment by kfbishop** [comment]
@nurivpr Can you please provide more details on your windows environment.  Version/Arch, and anything else that might help us diagnose these errors. thx

**Comment by triceam** [comment]
@nurivpr: as @kfbishop mentioned, it would be extremely helpful to know which version of Windows you're running, and what version of PowerShell you are running.   You can check the PowerShell version by running `$PSVersionTable.PSVersion` in the PowerShell terminal.   

The error message you are seeing seems like an older, unsupported version of either Windows or PowerShell (or both): 

```
The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

The `Invoke-WebRequest` feature was introduced in PowerShell 3, in 2012, so you're likely using an older version.  This installation script requires Windows 10 or newer.

**Comment by triceam** [comment]
We've been able to recreate this issue on a Windows 7 machine.   I'm pretty sure this is from an older system.  I've created a new work item to add version checking in the installation script to prevent similar issues on unsupported systems.

**Comment by kfbishop** [comment]
Pretty much full rewrite of windows installer in v1.2.  Resolved.
