### ISSUE TITLE
Aliases on Windows

### ISSUE THREAD

**Issue by triceam** [IBM-Cloud/ibm-cloud-developer-tools#3]
**Summary**
Windows installation does not handle alias creation yet.  See MacOS version for alias & update shortcuts

**Operating System**
Windows

-----------------------------------

**Development "done" checklist**

- [ ] Public Documentation/README updated
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by kfbishop** [comment]
Using standalone "idt.bat" file in win, and idt "bash" shell for lin/mac
