### ISSUE TITLE
Getting Warning about XCode but have XCode 9.x installed

### ISSUE THREAD

**Issue by mjperrins** [IBM-Cloud/ibm-cloud-developer-tools#33]
**Summary**
Getting Warning about XCode but have XCode 9.x installed

<img width="532" alt="screen shot 2018-01-13 at 11 31 10 am" src="https://user-images.githubusercontent.com/16599999/34908444-48835c1e-f855-11e7-90ac-3b5d37415a31.png">

```
[install_deps] WARN: Xcode does not appear to be installed on this system.
```
<img width="638" alt="screen shot 2018-01-13 at 11 28 51 am" src="https://user-images.githubusercontent.com/16599999/34908410-f7f5ac0c-f854-11e7-89ca-eb59bce30c5d.png">

**Steps to reproduce**
(include tooling version, platform, etc)
1. 

**Operating System**
Specify: (MacOS, Linux, Windows)

**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by triceam** [comment]
Closing: Dependency on Xcode and auto-installation of Cocoapods were removed from the installation script in https://github.com/IBM-Cloud/ibm-cloud-developer-tools/commit/cb1cd63aaebe09422cad88832495ca1f7b017256
