### ISSUE TITLE
json: cannot unmarshal number into Go struct field Error.code of type string

### ISSUE THREAD

**Issue by mgluhic10** [IBM-Cloud/ibm-cloud-developer-tools#53]
**Summary**
Hi Guys,

I am trying to manage stuff trough IBM CLI. I installed application and all dependencies but I am expirencing strange problems:
for example:
**ibmcloud sl dns zone-list**
this is the error:
**json: cannot unmarshal number into Go struct field Error.code of type string**

When I execute:

**root@test01:/home/Bluemix_CLI# ibmcloud dev help
NAME:
   bx dev - A CLI plugin to create, manage, and run applications on IBM Cloud

USAGE:
   bx dev command [arguments...] [command options]

VERSION:
   1.3.3**

Everything seems fine.

Can you help me with this?
**Steps to reproduce**
(include tooling version, platform, etc)
1. 

**Operating System**
Specify: (MacOS, Linux, Windows)
I am using Linux Ubuntu 16.04
**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by YouHang** [comment]
Hi @mgluhic10 , can you please post the trace log here? because I didn't reproduce this issue on my end.
You can use `ibmcloud config --trace=true` to open the trace log function.

BTW, ibmcloud dev is plugin to create, manage, and run applications on IBM Cloud. and ibmcloud sl is plugin for Softlayer. they were different plugins.

**Comment by YouHang** [comment]
Hi @mgluhic10, waiting API or client fix this issue

**Comment by mgluhic10** [comment]
Hi Johan,


I managed to solve issue. Everything is fine now.

Thanks for you response.

Milan

**Comment by YouHang** [comment]
glad to hear that ^^

**Comment by steveclay** [comment]
It sounds as those this is resolved, so I will close.  Please reopen if this is still a problem.  Thanks
