### ISSUE TITLE
Install failure to create IDT shortcut on Windows 10

### ISSUE THREAD

**Issue by afaism** [IBM-Cloud/ibm-cloud-developer-tools#55]
**Summary**
Running 
Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm
.biz/idt-win-installer')

The result is:

PS C:\Users\AlexanderFaisman> Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm
.biz/idt-win-installer')

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose
you to the security risks described in the about_Execution_Policies help topic at
https:/go.microsoft.com/fwlink/?LinkID=135170. Do you want to change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
[main] --==[ IBM Cloud Developer Tools - Installer for Windows, v1.2.0 ]==--
[install] Starting Installation/Update...
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:122 char:19
+     $pluginlist = C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin li ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_deps] Checking for external dependency: git
[install_deps] Checking for external dependency: docker
[install_deps] Checking for external dependency: kubectl
[install_deps] Checking for external dependency: helm
bx already installed
Checking for updates...
No update required. Your CLI is already up-to-date.
[install_bx] IBM Cloud CLI version:
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:241 char:3
+   C:\"Program Files"\IBM\Bluemix\bin\bx.exe --version
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Installing/updating IBM Cloud CLI plugins used by IDT...
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:253 char:17
+   $pluginlist = C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin list
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: Cloud-Functions
[install_plugins] Installing plugin 'Cloud-Functions'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: container-registry
[install_plugins] Installing plugin 'container-registry'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: container-service
[install_plugins] Installing plugin 'container-service'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: dev
[install_plugins] Installing plugin 'dev'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Checking status of plugin: sdk-gen
[install_plugins] Installing plugin 'sdk-gen'
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:261 char:9
+         C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin install -r $ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Running 'bx plugin list'...
C:\Program Files\IBM\Bluemix\bin\bx.exe : The term 'C:\Program Files\IBM\Bluemix\bin\bx.exe' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:265 char:3
+   C:\"Program Files"\IBM\Bluemix\bin\bx.exe plugin list
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files\IBM\Bluemix\bin\bx.exe:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

[install_plugins] Finished installing/updating plugins
Creating 'idt' script to act as shortcut to 'bx dev' command...
[install] Install finished.
[quit] --==[ Finished. Total time: 00:00:00 seconds ]==--

Press any key to continue...
PS C:\Users\AlexanderFaisman>

**Comment by steveclay** [comment]
@afaism I have some changes in this branch that might solve your problem if you want to try them out:  https://github.com/IBM-Cloud/ibm-cloud-developer-tools/tree/win-fix

**Comment by afaism** [comment]
Just tried, the output is
idt-win-installer.ps1:320 char:187
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:398 char:250
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:433 char:92
+ ... ss="description">Be notified when participating or @mentioned.</span>
+                                                                   ~
Missing property name after reference operator.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:433 char:92
+ ... ss="description">Be notified when participating or @mentioned.</span>
+                                                                   ~
The '<' operator is reserved for future use.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:493 char:226
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:507 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:762 char:291
+ ... TF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:2369 char:180
+ ... UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:2372 char:10
+ </form>  </div>
+          ~
The '<' operator is reserved for future use.
At C:\Users\AlexanderFaisman\Downloads\idt-win-installer.ps1:2388 char:24
+       <li class="mr-3">&copy; 2018 <span title="0.36037s from unicorn ...
+                        ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\Users\AlexanderFaisman\Downloads>

**Comment by steveclay** [comment]
Could you try with the latest version?  It is working cleanly on our Win10 test systems.  If you could also provide some details about your system, that might help if you still have problems.

**Comment by triceam** [comment]
Closing.  Was fixed in https://github.com/IBM-Cloud/ibm-cloud-developer-tools/pull/57

**Comment by springified** [comment]
I got the same error.  the script emits an error after this message 
Creating 'idt' script to act as shortcut to 'bx dev' command...
```


OK
Plug-in 'sdk-gen 0.1.12' was successfully installed into C:\Users\PrabhaSasikanth\.bluemix\plugins\sdk-gen. Use 'C:\Program Files\IBM\Cloud\bin\bx.exe plugin show sdk-gen' to show its details.
[install_plugins] Running 'ibmcloud plugin list'...
Listing installed plug-ins...

Plugin Name                            Version
cloud-functions/wsk/functions/fn       1.0.22
container-registry                     0.1.329
container-service/kubernetes-service   0.1.558
dev                                    2.1.4
sdk-gen                                0.1.12

[install_plugins] Finished installing/updating plugins
Creating 'idt' script to act as shortcut to 'bx dev' command...
Out-File : Illegal characters in path.
At line:325 char:29
+   Write-Output $idt_batch | Out-File -Encoding ascii $idt_command
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], ArgumentException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

[install] Install finished.
[quit] --==[ Finished. Total time: 00:02:17 seconds ]==--

Press any key to continue...
```

**Comment by kblauer** [comment]
I am also receiving the same error as @springified during the final step: Creating 'idt' script

`[install_plugins] Running 'ibmcloud plugin list'...
Listing installed plug-ins...

Plugin Name                            Version
sdk-gen                                0.1.12
cloud-functions/wsk/functions/fn       1.0.22
container-registry                     0.1.329
container-service/kubernetes-service   0.1.558
dev                                    2.1.4

[install_plugins] Finished installing/updating plugins
Creating 'idt' script to act as shortcut to 'bx dev' command...
Out-File : Illegal characters in path.
At line:325 char:29
+   Write-Output $idt_batch | Out-File -Encoding ascii $idt_command
+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], ArgumentException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

[install] Install finished.
[quit] --==[ Finished. Total time: 00:01:40 seconds ]==--`

**Comment by kblauer** [comment]
In the downloaded idt-win-installer,ps1 script from the IBM CLI install steps found here: https://console.bluemix.net/docs/cli/index.html#overview

The bug that leads to this error is on line 318 - if the idt script isn't written, it doesn't have a record in get-command.  Therefore, when the file tries to write on line 325, as shown in the error above, it has no value stored in the directory parameter ($idt_command) passed into Write-Output.  See code from script below.

```
$idt_command = get-command idt -erroraction 'silentlycontinue'
  if( $idt_command )  {
    # The command is set, use it's existing location
  } else {
    # Set to IBM Cloud install location
    $idt_command = 'C:\"Program Files"\IBM\Cloud\bin\idt.bat'
  }
  Write-Output $idt_batch | Out-File -Encoding ascii $idt_command
```

**Comment by triceam** [comment]
Technically, the installation actually was successful in both of these cases, just a shortcut script was not created (we are planning to remove this shortcut as soon as all associated docs have been updated).   We will look into it and see why its now failing with illegal chars in certain scenarios.

You should still be able to use the `ibmcloud` cli after seeing these messages.  @kblauer @springified can you confirm if the `ibmcloud` cli works?

**Comment by kblauer** [comment]
Yes, the `ibmcloud` cli does indeed work.  I ended up going into the installer script provided and extracting the idt.bat manually then placing it into the correct directory.  This also worked and I have the idt command.

**Comment by hajmsta** [comment]
idt-windows-installer.ps1
Please change $idt_command variable setting
original>   $idt_command = 'C:\"Program Files"\IBM\Cloud\bin\idt.bat'
fix >   $idt_command = 'C:\Program Files\IBM\Cloud\bin\idt.bat'
![installer_error](https://user-images.githubusercontent.com/40046158/50811719-ffb7ea80-1352-11e9-924c-2ecdb998e6f8.jpg)
