### ISSUE TITLE
Docker fails to install and Helm fails to start on Windows 10 Pro using idt

### ISSUE THREAD

**Issue by VidyasagarMSC** [IBM-Cloud/ibm-cloud-developer-tools#73]
**Summary**
I have seen other issues raised in relation to Helm installation failure. But today while I was trying to install required tools using idt installer on Windows 10 Pro machine, Docker failed to install throwing 404 error and Helm failed to start with access denied error

**Steps to reproduce**

1. Open Windows Powershell in Administrator mode on Windows 10 Pro
2. Run the command 

`Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')
`
3. git installs fine, Docker fails with 404, Kubectl, Helm and other ibmcloud plugins install.
4. Launch Command Prompt and run `helm`. Throws an error saying `Access Denied`.

**Operating System**
Windows 10 Pro

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by ibmrcruicks** [comment]
Docker installer MSI no longer available -- the Docker dependency in the idt install script needs to be addressed with installer exe
https://github.com/docker/for-win/issues/954

**Comment by steveclay** [comment]
Thank you for identifying this. We will look into updating the installer for the new exe.

**Comment by steveclay** [comment]
Until this problem is solved, I suggest installing any missing components manually as described here:   https://console.bluemix.net/docs/cli/ts_createapps.html#appendix . For Docker for Windows in particular, it can be installed from here: https://www.docker.com/get-started . FYI for any who are encountering this same problem.

**Comment by steveclay** [comment]
Fixed. Please try the updated version.
