### ISSUE TITLE
Linux installer does not recognize "Red Hat" as a distro

### ISSUE THREAD

**Issue by steveclay** [IBM-Cloud/ibm-cloud-developer-tools#81]
**Summary**
The Linux installer now supports more than Ubuntu, but checks explicitly for *RedHat* when some versions of that OS return *Red Hat*. The script needs to allow for this,.

**Steps to reproduce**
(include tooling version, platform, etc)
1. Install on a recent Red Hat version.

**Operating System**
Specify: (MacOS, Linux, Windows)
Linux - Red Hat

**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify (manual)

**Comment by triceam** [comment]
Fixed in https://github.com/IBM-Cloud/ibm-cloud-developer-tools/commit/fa0f969246168818d5e2d06b9d08bc87b17f3b4c
