### ISSUE TITLE
Commands to tag resources not present in the ibmcloud cli

### ISSUE THREAD

**Issue by chupman** [IBM-Cloud/ibm-cloud-developer-tools#88]
**Summary**

In the [cli documentation](https://console.bluemix.net/docs/cli/reference/ibmcloud/cli_resource_group.html#ibmcloud_resource_tags) there are commands listed to manage and list tags. None of those commands are present in the cli.

**Steps to reproduce**
(include tooling version, platform, etc)
1. install ibmcloud cli(tried with 0.12.1+a6d7092-2018-11-19T10:31:10+00:00, also updated to 0.13.1 and issue was still present)
2. login and set endpoint
3. run  `ibmcloud resource tags`

**Operating System**
Specify: (MacOS, Linux, Windows)
MacOS
**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)

```
$ ibmcloud resources
FAILED
'resources' is not a registered command. See 'ibmcloud help'.

$ ibmcloud resource help
NAME:
   ibmcloud resource - Manage resource groups and resources
USAGE:
   ibmcloud resource command [arguments...] [command options]

COMMANDS:
   cf-service-instance-migrate   Migrate a Cloudfoundry service instance into resource group
   group                         Show details of a resource group
   group-create                  Create a resource group
   group-update                  Update an existing resource group
   groups                        List resource groups
   quota                         Show details of a quota definition
   quotas                        List all quota definitions
   search                        Search resources using Lucene query syntax
   service-alias                 Show details of a service alias
   service-alias-create          Create an alias of a service instance
   service-alias-delete          Delete a service alias
   service-alias-update          Update an service alias
   service-aliases               List aliases for a service instance
   service-binding               Show details of a service binding
   service-binding-create        Create a service binding
   service-binding-delete        Delete a service binding
   service-bindings              Show bindings to the service alias
   service-instance              Show details of a service instance
   service-instance-create       Create a service instance
   service-instance-delete       Delete service instance
   service-instance-update       Update service instance
   service-instances             List service instances
   service-key                   Show details of a service key
   service-key-create            Create a service key
   service-key-delete            Delete a service key
   service-keys                  List service keys of service instance or service alias
   help, h                       Show help

Enter 'ibmcloud resource help [command]' for more information about a command.
```
-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by steveclay** [comment]
@chupman this repo is specifically for the IBM Cloud Developer Tools, which includes the `dev` plugin that sits on top of the `ibmcloud` CLI that provides the commands you're looking for. If you open an issue in this repo https://github.com/IBM-Cloud/ibm-cloud-cli-release/issues , you should get an answer to this problem.
