### ISSUE TITLE
Install won't start on Win 10 Ent x64

### ISSUE THREAD

**Issue by hpigula** [IBM-Cloud/ibm-cloud-developer-tools#92]
**Summary**
I downloaded idt-win-installer.ps1 on my win 10 64 bit, started it in Powershell after using `Set-Execution`
as admin and it shows below output.
 

**Steps to reproduce**
(include tooling version, platform, etc)
1. Download and try to install on latest Windows 10 

**Operating System**
Specify: (MacOS, Linux, Windows)

**Supporting details**
(Logs, stack traces, images, etc.  Wrap in `<detail> ... </detail>` tags as appropriate)
PS C:\Users\horacy\Downloads\myApp\data> C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:387 char:156
+ ... -auto js-user-status-form" action="/users/status?compact=1""&""amp;li ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:387 char:180
+ ... m" action="/users/status?compact=1""&""amp;link_mentions=0""&""amp;tr ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:387 char:278
+ ... -8" method="post"><input name="utf8" type="hidden" value="""&""#x2713 ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:403 char:63
+                   <span class="js-user-status-no-emoji-icon" >
+                                                               ~
Missing file specification after redirection operator.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:416 char:18
+               80 remaining
+                  ~~~~~~~~~
Unexpected token 'remaining' in expression or statement.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:502 char:185
+ ... -8" method="post"><input name="utf8" type="hidden" value="""&""#x2713 ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:507 char:14
+ </form>      </details-menu>
+              ~
The '<' operator is reserved for future use.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:554 char:244
+ ... -8" method="post"><input name="utf8" type="hidden" value="""&""#x2713 ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:572 char:93
+ ... escription">Be notified only when participating or @mentioned.</span>
+                                                                   ~
Missing property name after reference operator.
At C:\Users\horacy\Downloads\myApp\data\idt-win-installer.ps1:572 char:93
+ ... escription">Be notified only when participating or @mentioned.</span>
+                                                                   ~
The '<' operator is reserved for future use.
Not all parse errors were reported.  Correct the reported errors and try again.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
 

PS C:\Users\horacy\Downloads\myApp\data> 
-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify idt-Win-installer 
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by hpigula** [comment]
Ok close issue it just downloaded some html file instead script while using `Save link as` which resulted in wrong code inside file.

**Comment by steveclay** [comment]
OK, thanks for the update. I was wondering how this could be since the solution the error calls for is what is also in the script.  Will close.
