### ISSUE TITLE
Can't install analytics engine plugin in docker Dev Cloud CLI

### ISSUE THREAD

**Issue by araujof** [IBM-Cloud/ibm-cloud-developer-tools#99]
**Summary**
Attempting to install analytics-engine on a fresh docker container with the official CLI image returns an error.

**Steps to reproduce**
1. docker pull ibmcom/ibm-cloud-developer-tools-amd64
2. docker run -ti ibmcom/ibm-cloud-developer-tools-amd64
3. (optional) ibmcloud plugin repo-add Bluemix https://plugins.ng.bluemix.net
4. ibmcloud plugin install -r Bluemix analytics-engine

_Note:_ I also tried multiple variations of the above, including installing directly from the downloaded analytics-engine plugin binary, without success. I finally created a fresh Ubuntu container, installed the standalone IBM Cloud CLI, and was able to install the plugin directly from the binary. 

**Operating System**
Linux (CLI running on Docker)
Docker Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm 

**Supporting details**
/ # ibmcloud plugin install analytics-engine
Looking up 'analytics-engine' from repository 'IBM Cloud'...
Plug-in 'analytics-engine 1.0.142' found in repository 'IBM Cloud'
Attempting to download the binary file...
 10.21 MiB / 10.21 MiB [=============================================================================================================] 100.00% 2s
10706777 bytes downloaded
Installing binary...
FAILED
Unable to obtain plug-in's metadata. Error: fork/exec /tmp/BluemixFileDownload570754541/analytics-engine-linux-amd64-1.0.142: no such file or directory

-----------------------------------

**Development "done" checklist**

- [ ] Test case to verify
- [ ] Public Documentation updated
- [ ] Change added to "release notes" as appropriate
- [ ] Notification to stakeholders (OM, other squads, etc)

**Comment by archerzz** [comment]
@araujof the linux version of `analytics-engine` is built with CGO enabled, thus it requires glibc. Unfortunately, the docker image we provide is based on alpine linux which doesn't provide glibc. Glibc is **GPLv3** which will cause legal issues for us.

I'll notify the owner of `analytics-engine` to double check the necessity of glibc.

**Comment by archerzz** [comment]
Here is the similar issue on [docker alpine](https://github.com/gliderlabs/docker-alpine/issues/12)

And there is actually a [work-around](https://stackoverflow.com/questions/34729748/installed-go-binary-not-found-in-path-on-alpine-linux-docker) for this, but I don't want to adopt it, since GPLv3 is a legal issue.

**Comment by steveclay** [comment]
@araujof the problem is actually with the `analytics-engine` plugin, unfortunately. Are you able to use the work-around shared by Archer until that plugin can be fixed?
